//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHng.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Employee
    {
        public int Restaurant_Id { get; set; }
        public int Employee_Id { get; set; }
        public int RestaurantEmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant_Employee Restaurant_Employee1 { get; set; }
        public virtual Restaurant_Employee Restaurant_Employee2 { get; set; }
    }
}
